"""
Sandbox Executor — runs agent-generated Python visualization code safely.

The Analysis Agent generates matplotlib/plotly code as a string.
This executor writes it to a temp file and runs it in a subprocess with:
  - A non-interactive 'Agg' matplotlib backend
  - A read-only data.json injection (player data)
  - A 60-second timeout
  - Captured stdout/stderr for debugging
"""
import asyncio
import json
import os
import sys
import tempfile
import textwrap
import uuid
from pathlib import Path
from typing import Any

from ..utils.config import settings


# ── Sandbox Preamble (injected before every generated script) ──────────────────
_PREAMBLE = """
import json, os, sys, warnings
warnings.filterwarnings("ignore")

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np
import pandas as pd
import seaborn as sns

# Consistent dark sports theme
plt.rcParams.update({
    "figure.facecolor":  "#0D1117",
    "axes.facecolor":    "#161B22",
    "axes.edgecolor":    "#30363D",
    "axes.labelcolor":   "#C9D1D9",
    "xtick.color":       "#8B949E",
    "ytick.color":       "#8B949E",
    "text.color":        "#C9D1D9",
    "grid.color":        "#21262D",
    "grid.linestyle":    "--",
    "grid.alpha":        0.5,
    "legend.facecolor":  "#161B22",
    "legend.edgecolor":  "#30363D",
    "font.family":       "DejaVu Sans",
})

ACCENT   = "#00D4AA"
ACCENT2  = "#FF6B35"
ACCENT3  = "#4ECDC4"
PALETTE  = [ACCENT, ACCENT2, ACCENT3, "#A78BFA", "#F59E0B", "#EF4444"]

# Data & output injected by executor
with open(DATA_FILE) as _f:
    data = json.load(_f)

OUTPUT_DIR = CHART_OUTPUT_DIR
os.makedirs(OUTPUT_DIR, exist_ok=True)
"""


async def run_visualization_code(
    code: str,
    player_data: Any,
    run_id: str,
) -> dict[str, Any]:
    """
    Execute a generated Python visualization script in a subprocess.

    Args:
        code:        Python code string generated by the Analysis Agent.
        player_data: Any JSON-serialisable data (list of player dicts, etc.).
        run_id:      Unique run identifier (used for output directory).

    Returns:
        {
            "success": bool,
            "charts":  list of absolute chart file paths,
            "stdout":  captured stdout,
            "stderr":  captured stderr,
        }
    """
    chart_dir = settings.CHARTS_DIR / run_id
    chart_dir.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory() as tmpdir:
        # Write player data
        data_file = os.path.join(tmpdir, "data.json")
        with open(data_file, "w", encoding="utf-8") as f:
            json.dump(player_data, f, ensure_ascii=False)

        # Build the full script: constants + preamble + agent code
        constants = (
            f'DATA_FILE = r"{data_file}"\n'
            f'CHART_OUTPUT_DIR = r"{chart_dir}"\n'
        )
        full_script = constants + _PREAMBLE + "\n\n" + textwrap.dedent(code)

        script_file = os.path.join(tmpdir, f"viz_{uuid.uuid4().hex[:8]}.py")
        with open(script_file, "w", encoding="utf-8") as f:
            f.write(full_script)

        # Run in subprocess with timeout
        try:
            proc = await asyncio.create_subprocess_exec(
                sys.executable,
                script_file,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
                cwd=tmpdir,
            )
            stdout_bytes, stderr_bytes = await asyncio.wait_for(
                proc.communicate(), timeout=90.0
            )
            success = proc.returncode == 0
        except asyncio.TimeoutError:
            proc.kill()
            return {
                "success": False,
                "charts": [],
                "stdout": "",
                "stderr": "Visualization timed out after 90 seconds.",
            }
        except Exception as exc:
            return {
                "success": False,
                "charts": [],
                "stdout": "",
                "stderr": str(exc),
            }

    # Collect generated chart files
    charts: list[str] = []
    if chart_dir.exists():
        charts = [
            str(chart_dir / f)
            for f in sorted(os.listdir(chart_dir))
            if f.lower().endswith(".png")
        ]

    return {
        "success": success,
        "charts": charts,
        "stdout": stdout_bytes.decode("utf-8", errors="replace"),
        "stderr": stderr_bytes.decode("utf-8", errors="replace"),
    }
